version: 2
models:
  - name: dim_channels
    columns:
      - name: channel_id
        tests:
          - unique
          - not_null
  - name: fct_messages
    columns:
      - name: message_id
        tests:
          - unique
      - name: view_count
        tests:
          - assert_positive_value